- id: doi:10.48550/arXiv.2502.05485
  type: paper
  description: This work proposes a hierarchical vision-language-action (VLA) model that improves robot generalization by using off-domain data (like videos or simulations). Instead of predicting actions directly, a high-level model generates a 2D path, which guides a low-level controller. This approach leads to better transfer across domains and improves real-robot performance by 20% on average.
  image: images/HAMSTER_Thumbnail.png
  buttons:
    - type: website
      text: Website
      link: https://hamster-robot.github.io/#
  tags:
    - behaviour cloning
    - vision language action
    - ICRA 2025
  awards: 
    - Best Paper

- id: doi:10.48550/arXiv.1703.01656
  tags:
    - behaviour cloning