name: Update Publications

on:
  schedule:
    - cron: '0 0 * * *'  # Jeden Tag um Mitternacht
  workflow_dispatch:  # Damit du den Workflow auch manuell ausführen kannst

jobs:
  update-publications:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scholarly pyyaml

    - name: Run script to update publications
      run: |
        python scripts/update_publications.py
