name: Update Publications

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Abhängigkeiten installieren
        run: pip install scholarly pyyaml

      - name: Skript ausführen
        run: python scripts/update_publications.py

      - name: Änderungen committen und pushen
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add publications.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Publications"
          git push
